### ISSUE TITLE
Wording : préciser les questions

### ISSUE THREAD

**Issue by pachevalier** [laem/futureco#1]
Dans le formulaire sur "Mes douches", certaines questions ne sont pas assez précises : 

>  Combien de temps dure votre douche en général ? 

On suppose que c'est en minutes mais c'est pas écrit.

>  Combien prenez-vous de douches ? 

On suppose que c'est par semaine mais c'est pas sûr.

**Comment by laem** [comment]
C'est reglé, merci !
