### ISSUE TITLE
Séparer empreinte à l'usage et à la fabrication

### ISSUE THREAD

**Issue by Keirua** [laem/futureco#11]
Super boulot! C'est top d'avoir ce genre d'informations.
 
Je n'ai pas compris certains écrans. Que représentent les coûts exactement ?
 - téléphone, liseuse, ordinateur: coût à l'achat? à chaque rechargement?
 - imprimante: coût à l'achat? coût pour une ramette de papier ?
 - mon épargne: pourquoi de tels coûts (surtout que ça peut être très élevé)? j'ai bien une idée, mais ça mérite d'être précisé

J'imagine que c'est difficile (et je me doute que tu y as pensé), mais avoir les source de ces chiffres serait top pour creuser une question en particulier.

**Comment by laem** [comment]
Sur un simulateur comme pour le [téléphone](https://futur.eco/simulateur/électronique/téléphone/impact), tu peux cliquer sur `calcul` pour voir l'explication.

1) est-ce que tu avais vu ce lien ?

Malheureusement la source de tous ces objets électroniques est commune et il faut donc remonter à la page [électronique](https://futur.eco/documentation/électronique) pour la voir.

Je vais trouver un moyen de faire ruisseler la source aux pages filles :+1: 

2) est-ce que ça résolverai le problème des sources ?

En ce qui concerne la question du coût, pour tous les sujets électroniques, c'est bien fabrication + usage, c'est donc une estimation sur la durée de vie du produit, en sachant qu'en France, l'électricité étant presque décarbonée l'usage est en général négligeable.

Il faut que je trouve un moyen de clarifier ce point. Malheureusement, par exemple pour le sujet du bus et TGV etc. je n'arrive pas à savoir si les données de la RATP incluent la fabrication des véhicules... Bref, pour l'instant c'est pas clair mais on va faire mieux.

**Comment by pinage404** [comment]
il serait intéressant d'avoir un découpage des couts sur la totalité du cycle de vie : 

exemple pour les [téléphones](https://futur.eco/documentation/%C3%A9lectronique/t%C3%A9l%C3%A9phone/impact) : 

| type | production | utilisation (en france) | fin de vie (collecte + recyclage / destruction ...) | total |
| :-- | --: | --: | --: | --: |
| mobile basique | 16 | ~0 | ? | 16 |
| smartphone moins de 5 pouces | 32 | ~0 | ? | 32 |
| smartphone plus de 5 pouces | 38 | ~0 | ? | 38 |

**Comment by laem** [comment]
D'autant plus qu'on peut maintenant avoir accès à des rapports assez détaillés des constructeurs, exemple ici avec l'ultra portable haut de gamme de chez Lenovo : 

![Screenshot_20190930-095538_Adobe Acrobat](https://user-images.githubusercontent.com/1177762/65859462-8ccf2380-e368-11e9-998c-ab41ba33c3ea.jpg)
