### ISSUE TITLE
Rendre possible la recherche via une URL

### ISSUE THREAD

**Issue by ColinMaudry** [laem/futureco#159]
Les moteurs de recherche DuckDuckGo et Kagi donnent la possibilité de lancer des recherches sur certains sites directement depuis leur barre de recherche. Par exemple, !wikifr permet de n'effectuer la recherche que sur la version français de Wikipédia sur ces moteurs de recherche.

Plus généralement, les navigateurs permettent de créer des recherches personnalisées via des mots clés.

Tout ceci n'est possible que si le site en question permet le lancement d'une recherche via une URL. Dans le cas du bang !wikifr, c'est https://fr.wikipedia.org/wiki/Special:Search?search=[recherche]

Cette issue vise à permettre une telle recherche dans FuturEco voyage, par exemple :

https://futur.eco/voyage?search=[recherche]

**Comment by laem** [comment]
Très bonne idée ! C'est noté.

**Comment by laem** [comment]
Et c'est fait :)

**Comment by lefuturiste** [comment]
Il semble avoir une régression car ce système ne marche plus
Ex
https://futur.eco/voyage?search=Marseille

**Comment by laem** [comment]
Oui, c'est q qu'il faut utiliser : https://futur.eco/voyage?q=Marseille
