### ISSUE TITLE
Questionnaire transport

### ISSUE THREAD

**Issue by pachevalier** [laem/futureco#2]
Dans le questionnaire sur les transports quotidiens, je pense qu'il faut prendre en compte le multimodal. Par exemple, je prends le transilien + le bus.

Evaluer le nombre de kilomètre qu'on parcourt n'est pas évident. J'en ai aucune idée ;)

**Comment by laem** [comment]
Tout à fait, il faut pouvoir ajouter des type de transports, et j'aimerais bien aussi faire des suggestions (ex. un trajet pour aller prendre du pain, un trajet domicile-boulot en campagne, un trajet entre régions, un trajet pour des vacances à l'autre bout du pays, etc.)
