### ISSUE TITLE
Something went wrong! caractères non reconnus dans la zone de saisie de recherche

### ISSUE THREAD

**Issue by u4y0u** [laem/futureco#214]
Certains caractères frappés au clavier déclenchent l'affichage de la page "Something went wrong! , Try again"

Il y a le caractère '&' qui peut être utilisé dans la recherche d'un nom de commerce, exemple '**V & B**' (V and B) ou l'erreur se produit juste en saisissant le caractère espace ' ' après le '&'.

Il y a aussi les caractères '**(**' et '**)**' , exemple '**test (**' ou l'erreur se produit dès la saisie de la première parenthèse mais aussi si l'on utilise la parenthèse refermée seule. Je l'ai découvert lors de l'utilisation d'un copié collé ou ce caractère était resté.

**Comment by laem** [comment]
Merci pour le bug et la description précise et reproductible, du coup je les ai corrigés rapidement :)

**Comment by laem** [comment]
Tu peux regarder https://github.com/laem/futureco/commit/d5aab70adace3fa0ef89eeabae584500c433fe8a si tu veux : il s'agissait de manquements de ma part sur l'escape des chaines de caractères.
