### ISSUE TITLE
Clic sur imagerie de rue et accès au meta-catalogue panoramax inopérant. (imagerie de rue)

### ISSUE THREAD

**Issue by u4y0u** [laem/futureco#221]
Le lien vers l'imagerie de rue pointe toujours vers **https://panoramax.fr** qui et inopérant (?)
En revanche l'accès au méta-catalogue **https://api.panoramax.xyz** me semble plus adapté et surtout fonctionnel.

voir aussi:
https://forum.openstreetmap.fr/t/uuid-panoramax-comment-lutiliser/20482/11?u=u4y0u
pour l'utilisation du tag 'panoramax' et l'UUID en valeur.

voir https://github.com/laem/futureco/pull/222

**Comment by u4y0u** [comment]
Fait.oK

**Comment by u4y0u** [comment]
END

**Comment by laem** [comment]
Merci :)
