### ISSUE TITLE
fichier env.local

### ISSUE THREAD

**Issue by etiennejourdier** [laem/futureco#231]
Salut,
Je n'ai pas compris comment faire fonctionner le fichier env.local avec la clé maptiler. J'ai essayé de mettre le fichier dans le dossier voyage, puis dans app, puis dans futureco, et j'avais irrémédiablement l'erreur : 
```
⨯ app/voyage/Map.tsx (91:8) @ Component
 ⨯ Error: You have to configure env NEXT_PUBLIC_MAPTILER, see README
    at Component (./app/voyage/Map.tsx:127:15)
  89 |
  90 | 	if (process.env.NEXT_PUBLIC_MAPTILER == null) {
> 91 | 		throw new Error(
     | 		     ^
  92 | 			'You have to configure env NEXT_PUBLIC_MAPTILER, see README'
  93 | 		)
  94 | 	}
```

J'ai fini par utiliser export pour créer la variable d'environnement. Je suis preneur d'une explication pour geek débutant !

**Comment by laem** [comment]
Bonjour, 

dans mon fichier .env.local j'ai ça : 

``` 
VOYAGE=oui
NEXT_PUBLIC_MAPTILER=xyz
```
Il est à la racine du repo futureco. 

C'est étrange que ça ne marche pas chez toi. 

Tu  lances bien "yarn dev" pour ce soit next qui lance le serveur et aille récupérer le .env.local ?

**Comment by mawagusura** [comment]
C'est possible que la confusion vienne d'une [typo dans le readme](https://github.com/laem/futureco/blob/87757d7ebcfddc7eeeec6a8f1c7617c873a20e13/app/voyage/README.md?plain=1#L30) du dossier voyage: il faut que le fichier soit nommé `.env.local` et pas `env.local` (et doit etre placé à la racine).

**Comment by etiennejourdier** [comment]
Ah mazette c'était juste ça ! Et ça me parait tellement évident maintenant que je le lis ... J'ai corrigé dans la pull request #259. Merci !
