### ISSUE TITLE
Bug affichage 'Accès autorisé' [résolu]

### ISSUE THREAD

**Issue by u4y0u** [laem/futureco#240]
petit bug sur tous les affichages du tag 'accès' :

![Capture d’écran du 2024-04-05 18-14-45](https://github.com/laem/futureco/assets/54479065/373212da-9758-454d-850a-1128de4dbb25)

**Comment by laem** [comment]
Normalement ça a été réglé par une PR de contribution :) 

Est-ce que tu peux retester sur la fiche entreprise de ton retour de bug ?

**Comment by u4y0u** [comment]
C'est bon, plus de bug.
