### ISSUE TITLE
Trajet vélo court souvent plus long que celui sécurisé

### ISSUE THREAD

**Issue by Altonss** [laem/futureco#246]
Exemple: https://cartes.app/?allez=Point+sur+la+carte%7C%7C2.2971%7C48.8619-%3EPoint+sur+la+carte%7C%7C2.2970%7C48.8634

**Comment by laem** [comment]
Ah oui merci ! En effet, "le plus court" -> vélo de route actuellement, car le profil "le plus court" de BRouter donne des durées plus proches de la marche que du vélo :/

**Comment by laem** [comment]
OK, donc en fait c'est un profil marche ! Qui n'est plus trop utilisé. Je vais simplifier tout ça : deux profils, rando (trekking) vs sécurisé (safety), et on en ajoutera d'autres au besoin :)

**Comment by laem** [comment]
Oui, pardon, les gens de brouter expliquent que le court est devenu trekking maintenant.
