### ISSUE TITLE
Disfonctionnement de amenity = toilets dans la dernière version

### ISSUE THREAD

**Issue by u4y0u** [laem/futureco#250]
Bizarement, la recherche du bouton 'toilettes' ne fonctionne plus ce jour (27/04) alors qu'elle fonctionnait avant.

amenity = toilets

On pourrait d'ailleurs lui associer le tag 'building=toilets' qui est aussi parfois utilisé...

**Comment by laem** [comment]
Aaaah oui, l'ancien icône était blanc, je l'ai changé mais dans inkscape, et inkscape ne produit pas des SVG compatibles avec mon aglo qui les transforme en PNG en Javascript pour MapLibre qui ne prend que des PNG. Je corrige.
