### ISSUE TITLE
Nom de la ville coupé sur le plugin météo

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/futureco#275]
![image](https://github.com/laem/futureco/assets/87148630/67503aec-5b7f-4b0a-89b4-480bef6924fc)

Testé sur Firefox -> Windows 10

**Comment by laem** [comment]
Ah oui, pas propres les barres ! J'oublie toujours de vérifier d'autres navigateurs comme ici probablement un nav sur Windows.

**Comment by laem** [comment]
Peux-tu réessayer dans 5 minutes sur ta plateforme ?

**Comment by Jean-BaptisteC** [comment]
C'est tout bon merci :)
