### ISSUE TITLE
L'estimation de temps de parcours à pied est sous-estimé

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/futureco#287]
https://cartes.app/?style=base&allez=Gare+de+Metz%7Cw34110522%7C6.1768%7C49.1095-%3ESentier+des+Dix%7Cn8501439010%7C6.4564%7C48.1738&mode=walking#15/48.1738/6.4564/20/50

Un poil sous estimé :)

![image](https://github.com/laem/futureco/assets/87148630/3bb85903-730d-4238-88e7-e0d2358ed2b4)

**Comment by laem** [comment]
Bien vu ! Les jours n'étaient pas affichés :sweat_smile:

**Comment by laem** [comment]
Je te laisse retester dans 5 minutes puis fermer. Merci !

**Comment by Jean-BaptisteC** [comment]
C'est tout bon
