### ISSUE TITLE
[cartes.app] Ajouter des infobulles au survol des boutons

### ISSUE THREAD

**Issue by ColinMaudry** [laem/futureco#289]
Actuellement sur cartes.app, seule l'icône "Fond de carte" a une info bulle qui s'affiche au survol du curseur. Les icônes des boutons sont pas mal, mais je pense qu'elles ne sont pas assez explicites pour se passer d'une infobulle.

**Comment by laem** [comment]
Merci ! Fait dans 464ac9aa7bcf28c9b0c85dfa4836e3c7751d0b19 :)
