### ISSUE TITLE
Améliorer le démarrage de la web app sur mobile

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/futureco#299]
Depuis récemment, cartes.app me propose d'installer l'application sur mon téléphone, ce que j'ai fait.
Quand je la démarre, le menu de recherche est affiché avant d'être réduit avec une animation pas du tout fluide.

**Comment by laem** [comment]
Ah, il te le propose automatiquement ? C'est quel nav ? Tu as une capture ?

**Comment by Jean-BaptisteC** [comment]
https://github.com/laem/futureco/assets/87148630/9ee43e16-9a2d-4bd3-9001-faafa3138f9d

**Comment by laem** [comment]
Ah oui merci pour le bug, mais je voulais parler du navigateur qui te propose d'installer. Est-ce que c'est toi qui l'a fait via le menu, ou est-ce qu'il te l'a vraiment proposé ?

**Comment by Jean-BaptisteC** [comment]
C'est chrome qui m'a proposé de l'installer

**Comment by Jean-BaptisteC** [comment]
Le problème est corrigé
