### ISSUE TITLE
Mettre en avant les adresses dans la recherche

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/futureco#301]
Lorsque des adresses sont remontées dans la recherche, il n'y pas de titre et les adresses sont indiquées comme sous-titre.
Il serait plus adapté dans cette situation de mettre l'adresse comme titre et de retirer le sous-titre

![image](https://github.com/laem/futureco/assets/87148630/41b6fd7a-e42f-4e6a-bc42-630cb7934a8a)

**Comment by fouss** [comment]
#335
