### ISSUE TITLE
Plantage au redimensionnement du navigateur

### ISSUE THREAD

**Issue by waterced** [laem/futureco#306]
Bonjour laem,
En parcourant cartes.app j'ai réussi à le faire planter.
J'étais sur ce lien https://cartes.app/?transports=oui&filtre=tram&agence=TAN&routes=TAN%3A1-0#13.3/47.20894/-1.57872
sur navigateur Mozilla Firefox 126.0, windows 10.
Lorsque passe la fenetre de plein écran à plus petit (ou l'inverse, cf bouton sur l'image), le site plante.

![image](https://github.com/laem/futureco/assets/88687679/133c681a-3b33-4836-a5b5-1f17c54f098f)

![image](https://github.com/laem/futureco/assets/88687679/6d1fbc41-0d22-4e18-b9ea-5dc624bfd721)

**Comment by laem** [comment]
Tu pourras réessayer dans 2 minutes ? Normalement c'est résolu : )
