### ISSUE TITLE
Boutons inaccessibles dans la recherche par catégorie

### ISSUE THREAD

**Issue by waterced** [laem/futureco#316]
Lors de la recherche par catégorie, il m'est impossible de voir (et donc de cliquer sur) les boutons les plus à droite. Soit la barrede translation est présente mais sans bouton navette (capture d'écran 1), soit il n'y a pas du tout de barre (capture d'écran 2).
![image](https://github.com/laem/futureco/assets/88687679/08298ef0-322c-4c28-a4b6-2a0a082daba8)
![image](https://github.com/laem/futureco/assets/88687679/b13ec021-1a62-4dfa-952d-51c97a171dbb)

**Comment by Jean-BaptisteC** [comment]
De mon côté ça fonctionne avec une molette horizontale

**Comment by waterced** [comment]
Effectivement, j'y arrive finalement avec un clique molette + déplacement horizontal de la souris, mais ce n'est pas évident

**Comment by laem** [comment]
Au clic sur le bouton +, j'ouvre toutes les catégories : 
![Capture d’écran 2024-06-14 à 18 10 42](https://github.com/laem/futureco/assets/1177762/db29864b-1884-47a0-96bc-35e050fae7ae)
