### ISSUE TITLE
Fermer encart point d'intérêt après un nouveau clic

### ISSUE THREAD

**Issue by waterced** [laem/futureco#319]
Bonjour,

Exemple cas concret, à Bréhat dans la zone https://cartes.app/#15.06/48.84839/-3.00898

Au clic sur la Chapelle Saint-Michel, la fiche du batiment apparait, avec les tags OSM, la photo tirée du wikidata en haut, ainsi que d'autres photos Commons et un lien panoramax (cf image1). Jusqu'ici tout va bien.

Au clic, tout au nord de l'île, à coté (mais pas sur) le phare du paon, la fiche Chapelle Saint-Michel reste active avec les tags et la photo wikidata, alors que autres photos Commons et lien panoramax sont mis à jour à la nouvelle position.

Le résultat est la juxtaposition de photos prises à des endroits bien différents, est-ce souhaitable?

Proposition:

- [ ] Après avoir sélectionné une fiche OSM (ou "encart point d'intérêt") (matérialisée par `allez=` dans l'URL), en cas de nouveau clic sur la carte, en dehors d'un élément susceptible de donner un nouveau  `allez=` , il faudrait supprimer ce  `allez=` pour fermer cet encart point d'intérêt sans avoir à passer par la croix.

---
Image 1
![image1](https://github.com/laem/futureco/assets/88687679/f1dff4f5-70f2-4f7e-ab9c-74ab560ce39c)

---
Image 2
![image2](https://github.com/laem/futureco/assets/88687679/51e240f1-46c9-467a-b693-ae327cab7f31)

**Comment by laem** [comment]
Merci pour la description super précise du pb !

**Comment by laem** [comment]
Je te laisse tester, mais ça devrait être résolu :)

**Comment by waterced** [comment]
Bonjour leam,
Effectivement sur le cas d'usage de mon post initial c'est réglé, mais j'en ai trouvé un autre où cela pose problème.

Au clic sur la Chapelle Saint-Michel, la fiche du bâtiment apparait, avec les tags OSM, la photo tirée du wikidata en haut, ainsi que d'autres photos Commons et un lien panoramax (cf image1). Jusqu'ici tout va bien.

Au clic, légèrement plus au nord, sur le hameau de Crec'h Touric, la fiche de Crec'h Touric s'ouvre avec ses bons tags, mais la photo wikidata de la Chapelle Saint-Michel reste présente dans l'encart.

Le résultat est la juxtaposition d'une photo avec l'encart d'un autre lieu.

- [ ] Ne plus afficher les photos Commons qu'un nouvel appel à l'API Commons ne renvoie rien.


image1
![image](https://github.com/laem/futureco/assets/88687679/23f11dca-c2c8-4945-8df8-4ee96add0296)

image2
![image](https://github.com/laem/futureco/assets/88687679/25eca1db-30d6-4f46-a839-3db4b5930151)

**Comment by waterced** [comment]
(Je n'arrive pas à ouvrir de nouveau l'issue)

**Comment by waterced** [comment]
Autre exemple 

Au clic sur la Chapelle Saint-Michel, la fiche du bâtiment apparait, avec les tags OSM, la photo tirée du wikidata en haut, ainsi que d'autres photos Commons et un lien panoramax (cf image1). Jusqu'ici tout va bien.

Au clic, plus au nord, sur le hameau de Pont ar Prat, la fiche de Pont ar Prat s'ouvre avec ses bons tags, une photo Commons, mais la photo wikidata de la Chapelle Saint-Michel reste présente dans l'encart. (cf image2)

image1
![image](https://github.com/laem/futureco/assets/88687679/0692043c-004d-4d74-bdc8-9143a9751487)

image2
![image](https://github.com/laem/futureco/assets/88687679/4d4d5ad0-c120-4dc8-a0a6-6494444647f9)
