### ISSUE TITLE
Améliorer l'affichage des horaires d'ouverture

### ISSUE THREAD

**Issue by Jean-BaptisteC** [laem/futureco#322]
https://cartes.app/?allez=La+Laiterie+de+Metz%7Cn11308712423%7C6.1644%7C49.1068#17/49.1068/6.1644/20/50
![image](https://github.com/laem/futureco/assets/87148630/b2c89288-50a0-466a-93f2-56c12c1e6155)

- Afficher le jour le plutôt ou le commerce est ouvert en considérant que le lundi est le premier jour de la semaine
- Afficher le premier horaire d'ouverture de la journée à gauche

**Comment by laem** [comment]
![Capture d’écran 2024-06-14 à 18 42 05](https://github.com/laem/futureco/assets/1177762/cccff296-a22d-4422-8813-15f9fd11ff8f)

**Comment by Jean-BaptisteC** [comment]
Le deuxième point n'est pas corrigé :)
