### ISSUE TITLE
Scroller latéralement les horaires de transports

### ISSUE THREAD

**Issue by ColinMaudry** [laem/futureco#324]
![image](https://github.com/laem/futureco/assets/3747136/9a0019fa-99a9-4277-9175-f1e249fa8652)

Dans cet exemple, je ne peux pas voir l'heure à laquelle j'arriverais si je prends une des options 6:20. Il manque un moyen de scroller latéralement (desktop)

**Comment by laem** [comment]
Ce serait mieux d'avoir une barre de défilement, j'en conviens, mais maj + scroll ça devrait fonctionner, non ?

**Comment by ColinMaudry** [comment]
Ça devrait fonctionner effectivement, mais j'avoue que j'avais oublié cette possibilité. Elle est assez peu connue je pense, malheureusement.

**Comment by laem** [comment]
Je positionne le scroll au clic, ça vous convient :) ? 

![Recording 2024-06-19 at 18 56 17](https://github.com/laem/futureco/assets/1177762/e4ccc871-dcca-4bf3-b575-676759acd228)
