### ISSUE TITLE
Horaires d'ouverture

### ISSUE THREAD

**Issue by Cyril5C** [laem/futureco#327]
Salut,
Quand on déplie les horaires d'ouverture, l'heure actuelle se mélange avec les horaires.
<img width="369" alt="Capture d’écran 2024-06-06 à 11 44 03" src="https://github.com/laem/futureco/assets/64784806/d986d3cc-76a2-4681-8b33-e43a261b1f99">
Cyril.

**Comment by laem** [comment]
Merci ! Oui un problème facile à résoudre. C'est #322 non ?

**Comment by Cyril5C** [comment]
euh oui ça ressemble ;)
