### ISSUE TITLE
1 image = 50% du poids de la page 😱

### ISSUE THREAD

**Issue by pinage404** [laem/futureco#36]
cette simple ligne, ajoute 1.4Mo sur une page de 2.5Mo

https://github.com/laem/futureco/blob/7a7f4c6f64850c7c511b0774a334a62e25f2280e/source/sites/publicodes/HumanCarbonImpact.js#L96

l'effet est cool mais je ne pense pas qu'il vaut la peine de télécharger 1.4Mo

---

je propose une de ces solutions : 
* le plus simple est de supprimer cet effet
* compresser l'image
* découper l'image et la compresser pour réduire son poids
* utiliser une image SVG avec [`filter`](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
* faire un screenshot du rendu et utiliser [`border-image`](https://developer.mozilla.org/fr/docs/Web/CSS/border-image)

**Comment by laem** [comment]
Oulah, bien vu !!
