### ISSUE TITLE
Chargement des données trop long

### ISSUE THREAD

**Issue by laem** [laem/futureco#44]
C'est du à la fonction netlify utilisée pour récupérer les données en direct sur github. Je suppose que c'est la requête github qui est longue, les fonctions netlify sont sensées être performantes.
Sur pingdom-tools, on constate que la requête prend 1.6secondes :fearful:

**Comment by laem** [comment]
#32

**Comment by pinage404** [comment]
est-ce que le fichier pourrait etre mit en cache derrière un CDN ?

**Comment by laem** [comment]
J'avais fait cette histoire de fonction netlify pour deux raisons : 
- stocker du Yaml sur github mais servir du json pour éviter d'embarquer un parser lourd dans le site
- pouvoir mettre à jour les données sans builder le site à nouveau

À voir si on peut cacher le fichier dans la fonction netllify, sinon trouver un autre serveur.

**Comment by pinage404** [comment]
TL;DR je vois pas trop de problème à builder le site site à chaque modification

---

plus on ramène des étapes lors du build, moins les clients (dans ce cas, les browsers des utilisateurs) devront faire de calculs

je souhaite que les clients soient plus nombreux que le nombre de builds (je ne sais pas si c'est le cas actuellement)

donc je pense qu'il faudrait maximiser les calculs cotés builds pour minimiser de faire faire ces calculs cotés clients pour minimiser le nombre de calcul global

---

je ne connais pas Circle CI mais j'imagine qu'il est possible de générer le JSON à chaque merge, de le stocker quelques part et de fetch via le site ? (avec GitLab CI, je sais faire, c'est très simple)

**Comment by laem** [comment]
> pouvoir mettre à jour les données sans builder le site à nouveau
je voulais parler du build de laem/futureco, car c'est assez lourd (5-10 minutes)

Mais en effet, on peut builder laem/futureco-data, ce sera super rapide, je n'y avais pas pensé, merci 🙂 

C'est en effet bête de retranscrire le YAML en JSON à chaque visite sur le site. 9bc636c82ba8a000b2b0cc38a84b8d8f952ac969 permet de construire à chaque build https://futureco-data.netlify.com/co2.json 👍 

> je souhaite que les clients soient plus nombreux que le nombre de builds (je ne sais pas si c'est le cas actuellement)

Il y a ~50 visiteurs uniques par jour. C'est bof, mais plutôt encourageant vu l'absence de lien vers le site sur le Web 😅
