### ISSUE TITLE
Fusion futureco et futureco-data #Monorepo

### ISSUE THREAD

**Issue by pinage404** [laem/futureco#47]
je propose de fusionner les deux repos (dans des sous dossiers pour conserver la séparation des responsabilités)

pour faire des modifications sur le site, on est obligé d'avoir le repos futureco-data cloné dans le répertoire parent avec le nom `data` (ou de créer un dossier `data` contenant le fichier `co2.yaml`)

https://github.com/laem/futureco/blob/47890c43fb91346c13b5248e2af2ca872c1e7750/source/RulesProvider.js#L28

les deux projets ont l'air fortements liés

qu'en pensez-vous ?

**Comment by laem** [comment]
Yep, c'est une contrainte en effet.
L'avantage d'avoir 2 dépôts, c'est pour séparer les issues et PR. L'objectif c'est qu'un non développeur puisse aller voir les données, et les *issues* sans avoir tout le bruit du code (assez compliqué) de l'application en JS. 
En pratique, en mettant les deux dépôts dans un dossier futureco, donc futureco/data et futureco/site, et en ouvrant son environnement de dev sur futureco/, j'ai l'impression que le problème est résolu, non ?
Je peux clarifier la doc.

**Comment by pinage404** [comment]
quand j'ai récupéré le projet, j'ai fait

```bash
mkdir futureco
cd futureco
git clone git@github.com:laem/futureco.git
git clone git@github.com:laem/futureco-data.git
```

j'avais donc ça

```
futureco
├── futureco
└── futureco-data
```

et vu que le site ne fonctionnait pas (j'ai pas lu la doc, mais je voyais qu'il cherchait un truc dans le dossier `../data`), j'ai ajouté un lien symbolique (j'aurais pu rename)

```
futureco
├── data -> futureco-data
├── futureco
└── futureco-data
```

---

faut voir comment ça évolue

si lorsqu'on change les `data` on change aussi le site (et vice versa), le monorepo sera très utile

si les changements sont jamais sans rapport, peut etre qu'il faut garder séparé

---

si les dossiers sont biens nommés, un non-dev ne sera pas géné par un dossier à la racine regroupant tout le site

---

je ne sais pas si un non-dev fera vraiment des changements, ça demande beaucoup d'investissement : 
* une plateforme à découvrir
* il faut s'inscrire
* il faut comprendre l'interface, qui en plus est en anglais
* il faut comprendre cette histoire de fork, de commit, de PR

l'interface permet de simplifier beaucoup de choses, il y a toute la documentation possible sur internet

mais ça fait beaucoup de mini obstacles qui peuvent arriver à bout de la motivation de pas mal de personnes

je parle de non dev qui n'aurait pas eu une mini formation / explication, ou des amis devs

je suis peut etre trop péssimiste, et je ne sais pas comment résoudre ce potentiel problème

**Comment by laem** [comment]
> si les dossiers sont biens nommés, un non-dev ne sera pas géné par un dossier à la racine regroupant tout le site

C'est surtout pour les issues que j'ai une crainte, pas vraiment pour le code en effet.

> je suis peut etre trop péssimiste, et je ne sais pas comment résoudre ce potentiel problème

Oui en vrai je n'ai comme toi aucune idée de si la contribution d'un non-dev est possible sur github.
Par contre, il y a une stratégie qui me semble possible : un non-dev fait une correction ou un ajout directement sur futur.eco via un éditeur dans la page Web. Quand il termine on lui dit : "Merci, ta contribution est prise en compte. Tu peux suivre l'avancement ici (lien vers une PR github sur futureco-data). Certes, l'interface sera en anglais, et il y a un risque que ces histoires de PR, issues, commentaires, diff de fichiers etc. ce soit trop à encaisser, mais je pense qu'il y a moins de risque sir le repo ne contient que les modèles, et pas de code JS ou d'issues qui en parlent 😅

**Comment by laem** [comment]
Je ferme car le [contributing](https://github.com/laem/futureco-data/blob/master/CONTRIBUTING.md) de futureco-data me semble répondre en grande partie à ce point.

**Comment by pascoual** [comment]
Je me suis fait avoir aussi :). J'ai rien contre garder les deux séparer @laem le justifie bien :+1: .

Par contre il faut ajouter dans [contributing](https://github.com/laem/futureco-data/blob/master/CONTRIBUTING.md) la commande pour créer un lien symbolique ou préciser qu'il faut renommer.
Tu veux un PR @laem ou tu veux gérer ?

Le projet est ouvert sur la création de branche ou faut cloner ? Je trouve pas l'info sur l'interface GitHub :(.

**Comment by laem** [comment]
Je t'ai ajouté à l'équipe :)
