### ISSUE TITLE
affichage améliorable pour "Votre futur :" dans la TopBar

### ISSUE THREAD

**Issue by pinage404** [laem/futureco#48]
l'affichage de "Votre futur :" pourrait etre amélioré

![Screen Shot 2019-11-03 at 16 06 50](https://user-images.githubusercontent.com/6325757/68087623-fe166080-fe57-11e9-8c56-53d6947af34b.png)

une première étape a été de transformé l'espace en espace insécable

https://github.com/laem/futureco/commit/47890c43fb91346c13b5248e2af2ca872c1e7750

mais on pourrait aussi aggrandir la boite

**Comment by laem** [comment]
Tu as ce bug sur quelle appareil ? Sur Firefox bureau windows et sur android l'affichage est correct pour moi ?

**Comment by pinage404** [comment]
sur la page d'accueil, Firefox Linux en full HD

![image](https://user-images.githubusercontent.com/6325757/68431444-811a1c80-01b2-11ea-88b1-9ffdedb872ff.png)

**Comment by laem** [comment]
Le fix a été intégré.
