### ISSUE TITLE
Réflexions actuelles sur le simulateur journée

### ISSUE THREAD

**Issue by laem** [laem/futureco#54]

**Comment by jbp-git** [comment]
1. Axes : 
- Développer 
- Faire connaitre
- Comment sensibiliser

1. 1 Développer : 
- Maquette présentable pour ex diffusion journal
- Éléments restant à intégrer : amortissement des achat de biens / 
- Observer ce qui est fait ailleurs et identifier points de différenciation : lister
- Permettre pour l'utilisateur un après de l'utilisation de l'outil 

1. 2
Faire connaitre:  
- Contacter journaux avec maquette (ex article)
- Contacter partager c'est sympa pour préparer la diffusion de l'outil
- 

1.3 Comment sensibiliser: 
- Qui souhaite t'on toucher ? 1/ pers comme nous sensibilisés. 2/ personnes non sensibilisée qui lit les journaux et aime jouer sur son tél. 3/   
- Qu'est ce qui les touche ? catég1/  
- Que souhaitent t'ils ?

**Comment by laem** [comment]
Je transfères ce commentaire dans #53
