### ISSUE TITLE
PWA: Application non installable

### ISSUE THREAD

**Issue by pinage404** [laem/futureco#63]
En lançant l'audit des Chromium DevTools, dans la section Progressive Web App, on voit que l'app n'est pas installable parce qu'il n'y a pas de manifest.json

On pourrait utiliser https://www.pwabuilder.com/ pour en générer un

Je pense que Futur.eco est le cas d'usage parfait pour une PWA

**Comment by laem** [comment]
Il y a https://github.com/laem/futureco/blob/master/manifest.webmanifest donc quand même un semblant de PWA. Mais il est à améliorer grandement en effet !

**Comment by laem** [comment]
OK je comprends, ce fichier n'était pas copié dans dist/ à la compilation, donc pas trouvé par le navigateur malgré un lien dans le HTML

**Comment by laem** [comment]
#71
