### ISSUE TITLE
Veille produit

### ISSUE THREAD

**Issue by flolina** [laem/futureco#69]

**Comment by flolina** [comment]
Après réunion d'aujourd'hui avec @laem et Louis, nous avons décidé de procéder à une veille produit qui pourrait inspirer futureco. Des produits pas forcément reliés à la simulation d'empreinte carbone mais aussi des produits autour du jeu, de la construction pour représenter de manière ludique, simple et claire le bilan journée carbone d'une personne sous forme de jauge / crédits carbone. 

Nous pouvons stocker ici :

- Noms de produits inspirants
- Screenshots de produit
- Parcours utilisateurs 
- Fonctionnalités intéressantes

Une fois la veille effectuée, nous pourrons procéder à la réalisation de maquettes pour la première partie de futureco : inviter l'utilisateur à rentrer sa consommation de la journée et lui présenter son bilan

**Comment by laem** [comment]
J'en propose un suite à une idée de Louis : tetris. L'idée est là même que #33 : les formes s'empilent (dans notre cas des consommations de la journée) jusqu'à atteindre le plafond. 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Emacs_Tetris_vector_based_detail.svg/288px-Emacs_Tetris_vector_based_detail.svg.png)

**Comment by flolina** [comment]
https://www.gocompare.com/gas-and-electricity/carbon-footprint/

![go_carbon](https://user-images.githubusercontent.com/63866470/80532659-c28ac800-899c-11ea-9950-cd5d0904a005.png)

**Comment by LG33** [comment]
Le jeu de carte Carbon City Zero qui place l'empreinte carbone et les solutions à l'échelle de la ville :
Le Kickstarter : https://www.kickstarter.com/projects/1010climateaction/carbon-city-zero
Une vidéo pour comprendre comment il fonctionne : https://youtu.be/SAjxQ_y0D2A

**Comment by flolina** [comment]
J'imagine un bonhomme qui se déplace dans un monde vert au fur et à mesure de sa consommation et son monde change et meurt au fur et à mesure.

En termes de graphisme, je cite Monument Valley parce que c'est fou.

![image](https://user-images.githubusercontent.com/63866470/80794827-24b11c00-8b9b-11ea-9124-db952c85b115.png)

Dans la même idée de quelque chose de visuel qui change dans le temps, y a le projet d'un ami à moi :

https://www.antoinepuig.design/projects-fr/gaia

**Comment by flolina** [comment]
Je pense aussi au lieu du bloc carré à faire des bulles en termes de visualisation ? Et au fur et à mesure le rond se complete et devient la Terre 

Inspiration de Google

![image](https://user-images.githubusercontent.com/63866470/80795306-68585580-8b9c-11ea-8794-08ad5be52d4d.png)


Sinon

<img width="776" alt="Screenshot 2020-05-01 at 11 11 57" src="https://user-images.githubusercontent.com/63866470/80795376-99d12100-8b9c-11ea-9fbe-bce1631a5dd6.png">


https://observablehq.com/@d3/bubble-chart

**Comment by flolina** [comment]
https://yourplanyourplanet.sustainability.google/

Initiative de Google


![Screenshot 2020-05-01 at 13 36 48](https://user-images.githubusercontent.com/63866470/80802991-3d2c3100-8bb1-11ea-8725-fbd1dc51a30c.png)

![Screenshot 2020-05-01 at 13 40 52](https://user-images.githubusercontent.com/63866470/80803063-75cc0a80-8bb1-11ea-8a07-e42168a2cf7b.png)
![Screenshot 2020-05-01 at 13 41 05](https://user-images.githubusercontent.com/63866470/80803066-782e6480-8bb1-11ea-8ab1-b942155055e9.png)

**Comment by laem** [comment]
Géniales toutes ces idées ! 
Pour les bulles, c'est l'approche de https://north-app.com

J'aime beaucoup l'idée du fond qui change à mesure qu'on se rapproche des limites. Pour l'instant je l'avais "implémenté" via une couleur différente pour chaque brique de consommation ajoutée a bilan, mais ça peut en effet être le fond lui-même de l'app qui change, ce qui rendra probablement les briques elles-mêmes plus lisibles.

Pour faire tout un monde graphique derrière, ce serait génial mais il faut beaucoup d'heures de graphismes :)

**Comment by The-Minh** [comment]
https://shameplane.com
Ce que je trouve intéressant : 
- interface sobre et bien focus, avec quelques infos par écran
- il y a des infos pré-remplies (aléatoirement)
- on peut comparer l'impact carbone du vol en question vs des changements de styles de vie

![screencapture-shameplane-2020-05-04-14_46_57](https://user-images.githubusercontent.com/2910722/80967165-3520fb00-8e16-11ea-8473-06e408ce762f.png)

**Comment by laem** [comment]
Ce "simulateur" est super proche de l'idée du simulateur journée : 

https://justone.earth/spend-that-green/

![image](https://user-images.githubusercontent.com/1177762/82893488-61312700-9f51-11ea-8f0d-dd53470dd299.png)

**Comment by LG33** [comment]
Oh ! C'est très simple mais c'est pas mal !

**Comment by The-Minh** [comment]
Mettre une jauge au-dessus, tout simplement… Nice !
