### ISSUE TITLE
Erreur sur la page "trajet en avion"

### ISSUE THREAD

**Issue by Morendil** [laem/futureco#82]
Sous Chrome:
https://futur.eco/simulateur/transport/avion/impact

Dans la règle `transport . avion . impact carbone unitaire`,
✖️ L'unité de la règle est incompatible avec celle de sa formule
  Impossible de convertir l'unité 'km' en 'kgCO₂e / km'

Puis
```
react_devtools_backend.js:6 TypeError: Cannot read property 'call' of undefined
    at i (bootstrap:68)
r @ react_devtools_backend.js:6
eu @ publicodes.js:47
n.callback @ publicodes.js:47
fi @ publicodes.js:47
iu @ publicodes.js:47
pc @ publicodes.js:47
t.unstable_runWithPriority @ publicodes.js:55
qa @ publicodes.js:47
dc @ publicodes.js:47
Zu @ publicodes.js:47
(anonymous) @ publicodes.js:47
t.unstable_runWithPriority @ publicodes.js:55
qa @ publicodes.js:47
Wa @ publicodes.js:47
Ha @ publicodes.js:47
M @ publicodes.js:47
z @ publicodes.js:47
Jt @ publicodes.js:47
Xt @ publicodes.js:47
load (async)
Yt @ publicodes.js:47
Kt @ publicodes.js:47
Qo @ publicodes.js:47
lc @ publicodes.js:47
sc @ publicodes.js:47
uc @ publicodes.js:47
Zu @ publicodes.js:47
(anonymous) @ publicodes.js:47
t.unstable_runWithPriority @ publicodes.js:55
qa @ publicodes.js:47
Wa @ publicodes.js:47
Ha @ publicodes.js:47
L @ publicodes.js:47
Gt @ publicodes.js:47
bootstrap:68 Uncaught TypeError: Cannot read property 'call' of undefined
    at i (bootstrap:68)
```

Contexte: j'étais tenté de répondre à [ce tweet](https://twitter.com/leobenichou/status/1279037272395059202) avec le lien vers futur.eco ;)

**Comment by laem** [comment]
Merci @Morendil 
Tu peux essayer après un Ctrl-F5 (pour invalider le cache) ? 
Je crois que c'est un vilain bug de cache #19. Je n'avais pas réussi à le résoudre : https://github.com/laem/futureco-data/issues/80.

**Comment by Morendil** [comment]
Effectivement Cmd+Shift+R (équivalent de Ctrl-F5 je crois) affiche la page correctement, mais Cmd-R (recharger sans invalider le cache) affiche à nouveau une page blanche. Comme toi c'est OK quand je charge dans une fenêtre incognito.

**Comment by Morendil** [comment]
J'ai supprimé le service worker à la main et ça fonctionne. Désolé pour le doublon :)
