### ISSUE TITLE
Comparateurs thématiques

### ISSUE THREAD

**Issue by mquandalle** [laem/futureco#84]
L'idée est d'afficher l'impact carbone d'une action et de ses alternatives avec quelques questions bien ciblées, voire des curseurs à déplacer.

- vaisselle à la main ou avec un lave-vaisselle ? 
- liseuse ou livres papier ?
- douche ou bain ?
- voiture diesel d'occasion ou voiture électrique neuve ? 

C'est quelque chose qu'on fait timidement sur mon-entreprise.fr ([chômage partiel](https://mon-entreprise.fr/simulateurs/ch%C3%B4mage-partiel) et [statuts](https://mon-entreprise.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux)) et c'est un cas d'usage pour lequel j'aimerais améliorer l'API de publicodes.

**Comment by laem** [comment]
Super suggestion ! Je crois que ça rejoint https://github.com/laem/futureco/issues/59

**Comment by mquandalle** [comment]
Une question que je me pose : à partir de quand c'est écologique et/ou économique d'acheter un vélo si je garde ma voiture ?

- si j'ai 2 voitures et que je remplace par 1 voiture + 1 vélo, la question ne se pose pas, c'est directement positif 

- si j'ai une voiture et que j'achète 1 vélo, je passe à 1 voiture + 1 vélo
  - pour une petite voiture futur.eco me donne 0,16kco2/km à l'utilisation, fabrication d'un vélo 240kco2, donc il faut faire 240/0,16 = 1500 km de trajet pour amortir l'impact co2 de la fabrication du vélo
  - d'un point de vue économique vélo à 500€, voiture 5l au 100, 2€ le litre => 500/2/5*100 = 5000km pour rentabiliser l'achat 
- même calcul avec un vélo électrique
- même calcul avec une grosse voiture

**Comment by laem** [comment]
Intéressant ! Attention à prendre le coût total d'usage de la voiture, pas que l'essence. 
Pour les 160gCO2e, je pense aussi que c'est sous-estimé, faudrait creuser et mettre à jour.

**Comment by mquandalle** [comment]
Oui, l'idée est de raisonner en coût d'usage marginal. Donc il faut inclure l'usure des pneus et des plaquettes de freins liée au trajet supplémentaire, mais pas le coût de l'assurance qui est payée dans tous les cas.

**Comment by mquandalle** [comment]
Ici un calcul bien documenté qui donne 700km pour amortir l'impact de la fabrication d'un vélo non électrique https://view.publitas.com/trek-bicycle/trek-bicycle-2021-sustainability-report/page/30

(pardon c'est un peu hors sujet pour ce dépôt, possible que je bouge mes messages ailleurs si je persiste à creuser le sujet)

**Comment by laem** [comment]
Pas de souci ! 

Pour l'instant je fais un gros écart du sujet climat, mais je compte bien l'intégrer intégralement dans cartes.app. Ce sera un des éléments clef.
