### ISSUE TITLE
Erreur de type - règle impact avion

### ISSUE THREAD

**Issue by totakoko** [laem/futureco#92]
Hello,

J'ai eu une erreur javascript sur la page https://futur.eco/simulateur/transport/avion/impact avec un affichage de page blanche.
Dans ma console : 
![image](https://user-images.githubusercontent.com/8938024/117419977-6e0a1900-af1d-11eb-99ee-3869a28fd852.png)

Après avoir vidé le cache pour le site, la page s'affiche désormais mais l'avertissement sur l'erreur de type est toujours présent. :upside_down_face:

**Comment by laem** [comment]
Bonjour ! Merci pour l'erreur. En effet, ça semble être un pb de cache... il se peut que tu aies déjà visité cette page par le passé. 

J'envisage de rebaser futureco sur nosgestesclimat-site bientôt, et donc de réécrire une large partie du code. Donc désolé, mais je vais devoir laisser ça en suspens pour l'instant, tant que l'erreur n'affecte pas les "nouveaux" :/

**Comment by laem** [comment]
Je me permets de fermer, le code a bien changé depuis :)
